title: Adnan Sami Bhuiyan
description: Bangladeshi Cyber Activist & AI Enthusiast
baseurl: ""
url: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Custom variables
social:
  twitter: adnansami
  github: adnansami
  linkedin: adnansami
  email: contact@adnansami.com
