title: Kamrul Hossain | Cybersecurity Specialist
description: A dedicated engineering student from Bangladesh, deeply immersed in the realms of computer science and technology with a passion for cybersecurity and ethical hacking.
baseurl: ""
url: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
